version: '3'

services:
  postgres:
    image: postgres:latest
    container_name: airflow_psql
    environment:
      - POSTGRES_USER=airflow
      - POSTGRES_PASSWORD=airflow
      - POSTGRES_DB=airflow
      # Fernet Key
      # - FERNET_KEY=
    volumes:
      - ./pgdata:/var/lib/postgresql/data

  webserver:
    build: ./airflow
    container_name: airflow_webserver
    restart: always
    depends_on:
        - postgres
    environment:
      - LOAD_EXAMPLES=n
      - EXECUTOR=Local
      # Fernet Key
      # - AIRFLOW__CORE__FERNET_KEY=
    volumes:
      - ./airflow/dags:/usr/local/airflow/dags
      - ./airflow/plugins:/usr/local/airflow/plugins
    ports:
      - "8080:8080"
    healthcheck:
      test: ["CMD-SHELL", "[ -f /usr/local/airflow/airflow-webserver.pid ]"]
      interval: 30s
      timeout: 30s
      retries: 3

  nginx:
    image: nginx:latest
    container_name: airflow_nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx:/etc/nginx/conf.d
    depends_on:
      - webserver
